### ISSUE TITLE
Animate Avatars

### ISSUE THREAD

**Issue by serizawa-04013958** [SiTH-Diffusion/SiTH#11]
Hello.
I'm a reseacher at company and I would like to try to use this code.
When I animate avatars, it need to use editable human code, but checkpoint must be set.
I mention this point.
![image](https://github.com/user-attachments/assets/a4ebc0cf-b690-420d-88de-bff5d1f3b16b)

since there is no information about checkpoint, how can I use this code?
I tried to use .pth file which trained by Sith, but it does not work because of key error.
↓
    self.sdf_field.load_state_dict(checkpoint['sdf'])
KeyError: 'sdf'

**Comment by azuxmioy** [comment]
Hi,

For the editable human code, you need to use its checkpoint as mentioned in the [repo](https://github.com/custom-humans/editable-humans?tab=readme-ov-file#quick-start)

Since the checkpoint contains real human faces from other datasets please go to the website and agree with the agreement. 

Thanks!

**Comment by serizawa-04013958** [comment]
Thank you for replying immediately!!
If I'm at company, How can I apply it?
I need to fill university. 
![image](https://github.com/user-attachments/assets/c6f73d23-4497-490f-b1d3-7cec9cef2f90)

**Comment by azuxmioy** [comment]
Unfortunately - yes, a university email address is required. The dataset and code are under the IP of ETH Zurich and are restricted to non-commercial use only.

One possible solution is to involve a university collaborator in your project. Still, the project needs to be for research purposes only.
