### ISSUE TITLE
rendering code, animatable code

### ISSUE THREAD

**Issue by serizawa-04013958** [SiTH-Diffusion/SiTH#12]
Hello author.

Thank you for your great work
I'd like to rendering reconstructed model, but the rendering code is included in your repo?
When I look into editable human's object file, these repo needs mtl file, but SiTH output does not have this.
instead of mtl file, SiTH output includes RGB information in obj file? 
in that case, If possible I want to ask you to sharing code for process SiTH obj file for rendering and animation.

here is SiTH's obj file 
![image](https://github.com/user-attachments/assets/4931f51f-ce45-4115-b43b-c1c0295fccfa)

**Comment by azuxmioy** [comment]
Hi,

Maybe you are asking to create UV maps for the output?

We provide some information [here](https://github.com/SiTH-Diffusion/SiTH?tab=readme-ov-file#animation-ready-avatars)

There is a flag called `--save_uv` that allows you to generate mtl and UV files - which are compatible with the editable human pipeline.

**Comment by serizawa-04013958** [comment]
No, I have two asking.
1. I'd like to render reconstructed model in different views
2. change pose of reconstructed model (animatable)

in editable human code, it seems to have a 3D to 2D rendering and repose code.
but when I importing recon_obj, it has different format from thumanmodel, test model
(e.g., /editable-humans/data/test/mesh/mesh-f00181_smpl.obj).
then, I got some errors when I import SiTH model

`Traceback (most recent call last):
  File "/cig/common06nb/deserizk/editable-humans/demo.py", line 87, in <module>
    main(args)
  File "/cig/common06nb/deserizk/editable-humans/demo.py", line 39, in main
    evaluator.fitting_3D(32, '/cig/common06nb/deserizk/SiTH_old/data/neuman/meshes/00000_reco.obj', '/cig/common06nb/deserizk/SiTH_old/data/neuman/smplx/00000_smplx.obj', fit_rgb=True)
  File "/cig/common06nb/deserizk/editable-humans/lib/models/evaluator.py", line 271, in fitting_3D
    rgb, nrm, sdf = closest_tex(V.cuda(), F.cuda(), texv.cuda(), texf.cuda(), mats, coord.cuda())
  File "/cig/common06nb/deserizk/editable-humans/lib/ops/mesh/closest_tex.py", line 59, in closest_tex
    rgb = sample_tex(hit_Tp, hit_TM, materials)
  File "/cig/common06nb/deserizk/editable-humans/lib/ops/mesh/sample_tex.py", line 28, in sample_tex
    assert(max_idx > -1 and "No materials detected! Check the material definiton on your mesh.")
AssertionError`

**Comment by azuxmioy** [comment]
yes, I understand🙂

 if you use the `--save_uv` flag when running sith, there should be no error.

**Comment by serizawa-04013958** [comment]
Thank you so much!
let me try and I will tell the result later 👍

**Comment by serizawa-04013958** [comment]
It worked!!
thank you so much, and let me close issue.
