### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by serizawa-04013958** [SiTH-Diffusion/SiTH#13]
let me ask you about training time, and parameters.
SiTH training seems to take long time but batch size is only 4.
is it possible to fasten training? have you ever optimize parameters?

I'd like to ask the average training time and what diffusion model's code sith refered.

**Comment by azuxmioy** [comment]
You can find this information in the [Supplementary Material](https://openaccess.thecvf.com/content/CVPR2024/supplemental/Ho_SiTH_Single-view_Textured_CVPR_2024_supplemental.pdf) of our paper.

We tried the largest batch size that fits our GPUs. And as far as I know, the easiest way to speed up training is buying more GPUs🙂

FYI, the 1K-res model trained with 5000 scans took more than 1 month on 4 A100 GPUs

**Comment by serizawa-04013958** [comment]
Thank you for sharing info!!
Do you mean that 5000 scans is 5000 id in Thuman?
Thuman has only 2500 id even in Thuman2.1

And if you are fine, I'd like to discuss how to keep consistency of back view images.
For example, I want to input video as an input. but in each frame, generated backview has different textures.

**Comment by azuxmioy** [comment]
Currently, there's no direct solution to handle videos and temporal consistency. This is still an open and challenging problem.
