### ISSUE TITLE
How to obtain an animated avata

### ISSUE THREAD

**Issue by 12awei** [SiTH-Diffusion/SiTH#15]
I have obtained a textured mesh with a UV map，How to obtain an animated avatar next？

**Comment by azuxmioy** [comment]
Hi, have you tried https://github.com/custom-humans/editable-humans?

**Comment by 12awei** [comment]
Thank you for your reply. I will try it out now

**Comment by 12awei** [comment]
Hello author. I want to use the motion sequence you provided to animate characters, so I used the repose feature of editable humans.
![image](https://github.com/user-attachments/assets/bc73ee51-b847-447f-9ad0-cd980c6676d9)
When I use the smplx model in the motion sequence for repose, I will encounter
![image](https://github.com/user-attachments/assets/944fbb40-cbe1-453f-b1dc-132dbb74fe95)
Did I do something wrong? Please write me some advice.

**Comment by azuxmioy** [comment]
Hi, can you check whether the target mesh file is within [-1~1]? If not you might need to displace the mesh vertices before using it.

**Comment by 12awei** [comment]
thank! I have resolved this issue

**Comment by szhang67** [comment]
@12awei @azuxmioy Hi, I am also following your work on avatar reconstruction and reposing, and i haven't been able to get the access to editable human checkpoints files. Can you guys maybe share these files with me. which will only be used for academic model test purpose? Thx

**Comment by azuxmioy** [comment]
Hi @szhang67, please send your request through https://custom-humans.ait.ethz.ch/

Please note that it takes several days for the responsible staff to review. 

If you do not receive the link in 5 days, please send an email to custom.humans@gmail.com and inform me again.

**Comment by szhang67** [comment]
@azuxmioy THX for reply! I have sent a request through the link and I will check often if I am granted the access. Also, is there other similar retargeting methods you would recommend that I can use to repose my human avatar? Thanks
