### ISSUE TITLE
How to train with my dataset?

### ISSUE THREAD

**Issue by justinvo277** [SiTH-Diffusion/SiTH#18]
I want to train with my data set, what should I do? Currently, I have not been able to download the THuman 2.0 and 2.1 dataset (I have filled out the form and waited for a response), so I do not know what is included in that dataset.  And "..and its SMPL-X registration to the data folder:" how do I register SMPL-X for my dataset?

**Comment by azuxmioy** [comment]
Hi, 

Fitting SMPL-X to mesh is not a simple task in dataset creation. We implemented our own pipeline similar to 

https://github.com/DavidBoja/SMPL-Fitting
https://github.com/zju3dv/EasyMocap

Basically, involving 2D keypoint detection, 3D keypoint triangulation, and SMPL-X parameters fitting.
I would suggest you use the THuman or CustomHuman directly.
