### ISSUE TITLE
Questions about evaluating the CAPE dataset？

### ISSUE THREAD

**Issue by Jack171516** [SiTH-Diffusion/SiTH#19]
Dear Author, Hi, very nice work, I have a question about evaluating the CAPE dataset, in the paper I see that you say to use the CAPE test set provided in the ICON method with 100 meshes for quantitative evaluation. But I found that the CAPE test set provided in the ICON method seems to have 150 meshes, divided into “CAPE-FP” (50 meshes) and “CAPE-NFP” sets (100 meshes). Which part of the meshes are you talking about? I started to assume that it was the “CAPE-NFP” collection and then used its rendered images to generate the meshes and evaluated them, but the results seem to be very poor. Looking forward to your answer！

**Comment by azuxmioy** [comment]
Hi, I remember it's CAPE-NFP, the 100 meshes split. I have attached a list of gt meshes for your reference.

[file_list.txt](https://github.com/user-attachments/files/17437528/file_list.txt)

Regarding the poor results, did you get numbers that did not match the paper? Or are there some failure cases in challenging poses?
It would be great if you could share more details, so we can see which part is missing.

**Comment by Jack171516** [comment]
Thank you for your answer, my problem was evaluating CAPE and getting data that was way off from the paper.（The results are shown below.）
![cape_results](https://github.com/user-attachments/assets/fbc189de-6b44-4de0-9f98-b6d6a1f717ad)
The results inside your paper are this：
![paper_result](https://github.com/user-attachments/assets/59cfe39b-2609-461e-9a94-8487c469a72b)
Specifically, the CAPE test set I downloaded from https://cape.is.tue.mpg.de/, this place inside the website (second image) for icon use, is called icon_test.zip, which contains the CAPE and CAPE_3views folders.
![icon_test](https://github.com/user-attachments/assets/f742f565-71a8-4a2d-a58a-acfb5f8c4adf)
 And inside the CAPE/SCAN folder provides 150 real meshes, the pose.txt file inside (list of 100 meshes name) seems to be the CAPE-NFP part of the division recorded, I use the meshes recorded inside pose.txt as the real meshes from the 150 meshes, and then I use the rendered 0-degree rgba image provided inside the cape_3views folder as the real frontal image， input  to the SITH method  to estimate the smplx parameter to generate the backside image as well as the reconstructed texture mesh, and finally the reconstructed texture mesh is evaluated against the real mesh in front for the reconstruction metrics. After looking at the file_list.txt you gave me, I realized that it seems to be really different from what is recorded inside the pose.txt I used. It seems that some of the meshes recorded inside file_list.txt are not in the scan folder inside the cape folder downloaded above, which I find strange!

**Comment by azuxmioy** [comment]
So there are two problems now:
1. What is the correct data for the evaluation?

> I realized that it seems to be really different from what is recorded inside the pose.txt I used

There are 150 scans in the cape folder and 100 scans in the pose.txt. When you compare my file list, all the file names should be included in pose.txt right? The first number indicates ID, and the second number is angle. 

e.g. 0000_000_00215-**jerseyshort-pose_model-000200**.obj vs cape/**00215-jerseyshort-pose_model-000200**

2. The scale of the evaluation metrics seems totally wrong 

I think the reason is that the center of the GT scan and image are not aligned. As you can see, the center of the GT scan is not at the pelvis of the human body, but the center of the RGB image is the pelvis joint.
To evaluate 3D metrics, we first need to shift the GT scan to the same 3D origin. You can do this with the provided SMPL body mesh.

<img width="384" alt="Screenshot 2024-10-19 at 12 05 39 AM" src="https://github.com/user-attachments/assets/0de17187-3468-4ba1-9a40-d50343ae3e06">

**Comment by Jack171516** [comment]
About the first problem, I re-compare the contents inside pose.txt and file_list.txt, and found that I was wrong before, they should be the same, as shown in the following figure, if the cape/ is removed in the pose.txt file, and the different angles are not taken into account in the file_list.txt file, in fact, they are referring to the same mesh.
![pose-file_list](https://github.com/user-attachments/assets/08d12fc2-3125-4f5b-afbd-a721087310f7)

Regarding the second problem, yes, I didn't even think about aligning the GT scan with the centre of an image, which may indeed be the reason why the metrics are evaluated incorrectly, I'll give the solution you mentioned a try!
Have a nice day!

**Comment by Jack171516** [comment]
Dear author, could you provide the reference code for moving the GT scan to the same 3D origin? I've tried it for the last two days and I still can't realize it .
And I found that the reconstructed mesh in the cape dataset seems to be different from the GT scan size scale as well, how to solve it?

**Comment by Jack171516** [comment]
Dear author, could you provide the reference code for moving the GT scan to the same 3D origin? I've tried it for the last two days and I still can't realize it .
And I found that the reconstructed mesh in the cape dataset seems to be different from the GT scan size scale as well, how to solve it?

**Comment by azuxmioy** [comment]
Although I don't have the data processing code for CAPE now, you can find how I aligned THuman scans with the provided SMPL-X meshes similarly. 

https://github.com/SiTH-Diffusion/SiTH/blob/main/tools/align_thuman.py#L51

I can also provide the processed meshes we used for evaluation. Please drop an email to custom.humans@gmail.com

**Comment by Jack171516** [comment]
Okay, thanks for your reply.
