### ISSUE TITLE
openpose

### ISSUE THREAD

**Issue by jinnan-chen** [SiTH-Diffusion/SiTH#2]
Hi, thanks for great work!
For openpose preprocessing, how to get the json file as the example given? Just using the offical openpose by Caffe or are there some workaround ways by pytorch? Thanks!

**Comment by azuxmioy** [comment]
Hi,

We used the original openpose binary and the suggested command to get these JSON files. 
https://github.com/CMU-Perceptual-Computing-Lab/openpose

Any keypoint detector that produces COCO25 body + hand + face keypoints in a similar format should be compatible.

Please refer to the loading function if you want to use other pose predictors
https://github.com/SiTH-Diffusion/SiTH/blob/main/fitting/utils/kps.py#L360

Thanks and best regards!
