### ISSUE TITLE
Documentation: Effects of guidance_scale and conditioning_scale parameters on reconstruction quality

### ISSUE THREAD

**Issue by emircetinmemis** [SiTH-Diffusion/SiTH#23]
## Background
In reconstruct.py, there are two important parameters that seem to affect the image generation quality:

1. `guidance_scale` (default: 3.5)
2. `conditioning_scale` (default: 1.0)

## Question
I would like to understand how these parameters influence the generated back-view images:

### For guidance_scale (CFG):
- What are the expected effects when we lower this value from the default 3.5?
- What are the expected effects when we increase it?
- What is the recommended range for this parameter?

### For conditioning_scale:
- What are the expected effects when we lower this value from the default 1.0?
- What are the expected effects when we increase it?
- What is the optimal range for different use cases?

## Purpose
Understanding these parameters would help users better tune the reconstruction process for optimal results. Clear documentation about their effects would be valuable for the community.

## Current Configuration
```python
parser.add_argument(
    "--guidance_scale",
    type=float,
    default=3.5,
    help="classifier free guidance scale"
)
parser.add_argument(
    "--conditioning_scale",
    type=float,
    default=1.0,
    help="Controlnet conditioning scale"
)
```
Sample output;
![image](https://github.com/user-attachments/assets/77581779-2faf-4cb5-893d-97e639c0a3be)

**Comment by azuxmioy** [comment]
Hi,

Classifier-free guidance(cfg):
https://arxiv.org/pdf/2207.12598

guidance_scale is the weight of the classifier-free guidance. The purpose is to add conditions to the denoising process. 
The noise prediction at each step is defined as: $\epsilon = w \cdot \epsilon_c + (1-w) \cdot \epsilon_u$ , where $\epsilon_c$ and  $\epsilon_u$ are conditional and unconditional noise prediction. The cfg weight in Stable Diffusion is set to 7.5. We found that 2.5~3.5 empirically works well in our model.


ControlNet
https://arxiv.org/pdf/2302.05543

The ControlNet model is about making feature modifications given additional image conditions. 

conditioning_scale is the weight of how much we want to add the residuals to the original feature maps.
conditioning_scale is set to 1.0 during training, and shouldn't be changed in most cases.

**Comment by emircetinmemis** [comment]
> Hi,
> 
> Classifier-free guidance(cfg): https://arxiv.org/pdf/2207.12598
> 
> guidance_scale is the weight of the classifier-free guidance. The purpose is to add conditions to the denoising process. The noise prediction at each step is defined as: ϵ = w ⋅ ϵ c + ( 1 − w ) ⋅ ϵ u , where ϵ c and ϵ u are conditional and unconditional noise prediction. The cfg weight in Stable Diffusion is set to 7.5. We found that 2.5~3.5 empirically works well in our model.
> 
> ControlNet https://arxiv.org/pdf/2302.05543
> 
> The ControlNet model is about making feature modifications given additional image conditions.
> 
> conditioning_scale is the weight of how much we want to add the residuals to the original feature maps. conditioning_scale is set to 1.0 during training, and shouldn't be changed in most cases.

Thank you in adnvance, for the clear and detailed explanation! This helps a lot.
