### ISSUE TITLE
Problem in side view... 

### ISSUE THREAD

**Issue by sahilshukla3003** [SiTH-Diffusion/SiTH#7]
Great work! How can one improve the area around neck, ears and chin ( i have tried using --erode_iter but still no improvement )

![Screenshot from 2024-06-20 18-41-24](https://github.com/SiTH-Diffusion/SiTH/assets/124785012/3aee06cd-ceb5-4b42-9247-929285e38b60)

**Comment by azuxmioy** [comment]
Hi,

Thanks for the message and sorry for the late response. Just came back from the conference. 

The side-view problem is expected as we did not fully address it in our CVPR version🙂
Changing the parameters may reduce some artifacts but won't give you clear ears and hair for sure. 
How to hallucinate multi-view consistent and aligned side appearance is still an interesting research problem. We leave this for future research.

Thanks
