### ISSUE TITLE
from recon.ops.mesh.load_obj import load_obj

### ISSUE THREAD

**Issue by Sosekie** [SiTH-Diffusion/SiTH#8]
Hello, I think you've put load_obj.py in recon.datasets but not in recon.ops.mesh maybe:
# from recon.ops.mesh.load_obj import load_obj
from recon.datasets.load_obj import load_obj

**Comment by azuxmioy** [comment]
Hi,

Thanks for letting me know. I changed the folder structure when releasing the training code and didn't have time to check all the import paths before the CVPR conference.

The `ops` folder is now in `recon.models`; I have updated the code accordingly. 

Thanks!
